export enum ExampleId {
  Setup = 'setup',
  Reactive = 'reactive',
  Confirm = 'confirm',
  ConfirmShorthand = 'confirm-shorthand',
  MessageBoxShorthand = 'message-box-shorthand',
  NamePrompt = 'name-prompt',
  Dismissal = 'dismissal',
  SizeOverride = 'size-override',
  BootstrapFullscreen = 'bootstrap-fullscreen',
  CustomFullscreen = 'custom-fullscreen',
  NonDismissible = 'non-dismissible',
  ScrollableBody = 'scrollable-body',
  Unstyled = 'unstyled',
  ShowUntil = 'show-until',
  ShowUntilCondition = 'show-until-condition',
  ProgrammaticRef = 'programmatic-ref',
  MessageBoxOk = 'message-box-ok',
  MessageBoxOkCancel = 'message-box-ok-cancel',
  MessageBoxYesNo = 'message-box-yes-no',
  MessageBoxProjection = 'message-box-projection',
}
