export enum ExampleId {
  Setup = 'setup',
  QuickStart = 'quick-start',
  Reactive = 'reactive',
  ConfirmShorthand = 'confirm-shorthand',
  MessageBoxShorthand = 'message-box-shorthand',
  MessageBoxLowLevel = 'message-box-low-level',
  MessageBoxProjection = 'message-box-projection',
  Confirm = 'confirm',
  Dismissal = 'dismissal',
  NamePrompt = 'name-prompt',
  SizeOverride = 'size-override',
  ScrollableBody = 'scrollable-body',
  NonDismissible = 'non-dismissible',
  BootstrapFullscreen = 'bootstrap-fullscreen',
  CustomFullscreen = 'custom-fullscreen',
  Unstyled = 'unstyled',
  ReactiveChain = 'reactive-chain',
  ShowUntil = 'show-until',
  ShowUntilCondition = 'show-until-condition',
  ProgrammaticRef = 'programmatic-ref',
}
